file:
  to:
    load: deliveries.json

spring:
  datasource:
    url: jdbc:h2:mem:orders
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring:
      jpa.database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false
        dialect: com.gorillas.order.delivery.receiving.config.H2DialectExtended
  h2:
    console.enabled: true

logging:
  level:
    org:
      hibernate:
        type: debug